/**
 * Pipeline Type Definitions
 *
 * This file contains all type definitions for the new pipeline architecture.
 * These types define the data structures used throughout the pipeline nodes.
 */

import { HumanMessage, AIMessage } from '@langchain/core/messages';
import { MapMarker, MapPolygon } from '../services/tools/schemas.js';

/**
 * ExtractedIntent - Represents the user's intent extracted from their message
 *
 * This is the output of the Intent Extraction node (Node 1).
 */
export interface ExtractedIntent {
  /** Natural language query describing what the user wants */
  query: string;

  /** Geographic location (city, address, region, etc.) */
  location: string;

  /** Types of places the user is looking for (e.g., ["hotel", "restaurant", "ski_resort"]) */
  placeTypes: string[];

  /** Extracted constraints and filters from the user's query */
  filters: {
    /** Maximum price/budget */
    maxPrice?: number;

    /** Minimum price */
    minPrice?: number;

    /** Number of bedrooms (for real estate) */
    beds?: number;

    /** Number of bathrooms (for real estate) */
    baths?: number;

    /** Cuisine type (for restaurants) */
    cuisine?: string;

    /** Features/amenities (e.g., ["pool", "parking", "wifi"]) */
    features?: string[];

    /** Date range (for hotels, events) */
    dates?: string;

    /** Medical specialty (for healthcare) */
    specialty?: string;

    /** Budget per night (for hotels) */
    budgetPerNight?: number;

    /** Star rating (for hotels) */
    starRating?: number;

    /** Number of guests */
    guests?: number;

    /** Distance/radius from location */
    radius?: number;

    /** Open now? */
    openNow?: boolean;

    /** Minimum rating */
    minRating?: number;

    /** Any other filters as key-value pairs */
    [key: string]: any;
  };

  /** Should we display results on the map? */
  requiresMap: boolean;

  /** Does this query require distance/travel-time calculations (isochrone)? */
  requiresDistance: boolean;

  /** Is this query about comparing places? */
  requiresComparison?: boolean;
}

/**
 * GeneratedQuery - Search queries generated by the LLM
 *
 * This is the output of the Query Generation node (Node 2).
 */
export interface GeneratedQuery {
  /** Array of optimized search queries (2-4 queries typically) */
  queries: string[];

  /** Search strategy to use */
  searchStrategy: 'multi_source' | 'single_authority' | 'aggregator' | 'direct';

  /** Maximum number of results to fetch per query */
  maxResults: number;

  /** Suggested domains/websites for this query (optional) */
  domains?: string[];

  /** Search parameters/hints */
  hints?: {
    /** Should we prioritize recent results? */
    recent?: boolean;

    /** Should we filter by location in search? */
    geoFilter?: boolean;

    /** Any other search hints */
    [key: string]: any;
  };
}

/**
 * ScrapedPage - Represents content scraped from a web page
 */
export interface ScrapedPage {
  /** URL of the scraped page */
  url: string;

  /** Page content in markdown format */
  markdown: string;

  /** Page title */
  title?: string;

  /** Timestamp when scraped */
  scrapedAt: Date;

  /** Whether scraping was successful */
  success: boolean;

  /** Error message if scraping failed */
  error?: string;
}

/**
 * PlaceData - Structured data for a single place
 *
 * This is extracted from scraped content by the Data Extraction node (Node 4).
 */
export interface PlaceData {
  /** Place name */
  name: string;

  /** Full address */
  address: string;

  /** Coordinates if available in the source */
  coordinates?: {
    lat: number;
    lng: number;
  };

  /** Rating (0-5 scale typically) */
  rating?: number;

  /** Number of reviews */
  reviewCount?: number;

  /** Price level ("$", "$$", "$$$", "$$$$") or actual price */
  priceLevel?: string;

  /** Numeric price if available */
  price?: number;

  /** Description/summary */
  description?: string;

  /** Source URL */
  url: string;

  /** Phone number */
  phone?: string;

  /** Website */
  website?: string;

  /** Business hours */
  hours?: string;

  /** Amenities/features */
  amenities?: string[];

  /** Photos/images */
  photos?: string[];

  /** Category-specific metadata */
  metadata: {
    /** For hotels: check-in/check-out times */
    checkIn?: string;
    checkOut?: string;

    /** For restaurants: cuisine type */
    cuisine?: string;

    /** For real estate: bedrooms, bathrooms */
    beds?: number;
    baths?: number;
    sqft?: number;

    /** For healthcare: specialty, accepting new patients */
    specialty?: string;
    acceptingNewPatients?: boolean;

    /** Any other metadata */
    [key: string]: any;
  };
}

/**
 * SearchResult - Raw search result from search engine
 */
export interface SearchResult {
  /** Page title */
  title: string;

  /** URL */
  url: string;

  /** Snippet/description */
  snippet?: string;

  /** Position in search results */
  position?: number;
}

/**
 * GeoChatState - Complete state for the pipeline graph
 *
 * This represents the data that flows through all nodes in the pipeline.
 */
export interface GeoChatState {
  // ===== Input =====
  /** User's original message */
  userMessage: string;

  /** Thread ID for conversation context */
  threadId: string;

  // ===== Node 1: Intent Extraction =====
  /** Extracted intent from user message */
  extractedIntent: ExtractedIntent | null;

  // ===== Node 2: Query Generation =====
  /** Generated search queries */
  generatedQueries: GeneratedQuery | null;

  // ===== Node 3: Search & Scrape =====
  /** Raw search results */
  searchResults: SearchResult[];

  /** Scraped page content */
  scrapedContent: ScrapedPage[];

  // ===== Node 4: Data Extraction =====
  /** Extracted structured place data */
  extractedPlaces: PlaceData[];

  // ===== Node 5: Geocoding =====
  /** Map markers with geocoded coordinates */
  markers: MapMarker[];

  /** Map polygons (isochrones, boundaries, etc.) */
  polygons: MapPolygon[];

  // ===== Node 6: Summarization =====
  /** Final AI-generated message/summary */
  finalMessage: string;

  // ===== Metadata & Error Handling =====
  /** Errors encountered during pipeline execution */
  errors: Array<{
    node: string;
    error: string;
    timestamp: Date;
  }>;

  /** Progress tracking */
  progress: {
    currentStep: string;
    percentComplete: number;
  };

  /** Conversation messages (for multi-turn support) */
  messages?: Array<HumanMessage | AIMessage>;
}

/**
 * Pipeline execution result
 */
export interface PipelineResult {
  /** Final AI message */
  message: string;

  /** Map markers to display */
  markers: MapMarker[];

  /** Map polygons to display */
  polygons?: MapPolygon[];

  /** Thread ID */
  threadId: string;

  /** Any errors that occurred */
  errors?: Array<{
    node: string;
    error: string;
  }>;

  /** Execution metadata */
  metadata?: {
    executionTime?: number;
    nodesExecuted?: string[];
  };
}

/**
 * Streaming event types for progressive updates
 */
export type StreamEvent =
  | {
      type: 'map_update';
      marker: MapMarker;
      progress: {
        current: number;
        total: number;
      };
    }
  | {
      type: 'progress';
      step: string;
      message: string;
      percent: number;
    }
  | {
      type: 'error';
      node: string;
      error: string;
    }
  | {
      type: 'complete';
      result: PipelineResult;
    };

/**
 * Node function signature
 * Each node takes the current state and returns an update to the state
 */
export type NodeFunction<T = Partial<GeoChatState>> = (
  state: GeoChatState
) => Promise<T> | T;
